demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include
from blogpost import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home.as_view(), name="home"),
    path("blog/", views.home.as_view(), name="home"),
    path("blog/blogs/", views.BlogList.as_view(), name="blog-list"),
    path("blog/<int:pk>/", views.BlogDetail.as_view(), name="blog-detail"),
    path("blog/blogger/<int:pk>/", views.AuthorDetail.as_view(), name="author-detail"),
    path("blog/bloggers/", views.AuthorList.as_view(), name="author-list"),
    path("blog/<int:pk>/create/", views.CommentFun.as_view(), name="comment"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", views.Signup.as_view(), name="sign-up"),
    path("add/<int:pk>/", views.BlogAdd.as_view(), name="blog-add"),
    path("blog/search/",views.SearchFun.as_view(), name="blog-search")
]

demo/blogpost/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    country = models.CharField(max_length=100)
    birth_date = models.DateField(blank=True, null=True)
    status = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager() 

    def __str__(self):
        return self.email
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    blog = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.title


class Comment(models.Model):
    #TODO:Rename to user
    username = models.ForeignKey(User,on_delete=models.CASCADE,related_name="ucomments") 
    #TODO: Rename to Blog
    commentblog = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    comment = models.TextField(blank=True, null=True)
    comment_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.comment[:75] if len(self.comment) > 75 else self.comment

demo/blogpost/forms.py
from django import forms
from .models import Comment, Post, User
from django.contrib.auth.forms import UserCreationForm


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["username", "commentblog", "comment"] 
        exclude = ["commentblog"]

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
            "country",
            "birth_date",
            "password1",
            "password2"
        ]
        labels = {
            "email": "Email",
            "first_name": "First Name",
            "last_name": "Last Name",
            "country": "Country",
            "birth_date": "Birthdate",
            "password1":"Password",
            "Password2":"Password confirmation" 
        }
        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "country": forms.TextInput(attrs={"class": "form-control"}),
            "birth_date": forms.DateInput(attrs={"class": "form-control","type":"Date"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class BlogAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'blog']

class SearchForm(forms.Form):
    search = forms.CharField(label='Search', max_length=100, required=False)

demo/blogpost/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from blogpost.models import Post, Comment, User
from django.views.generic import DetailView, ListView, TemplateView, CreateView
from .forms import SignUpForm, BlogAddForm, CommentForm, SearchForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.db.models import Count


class home(TemplateView):
    template_name = "blogpost/home.html"


class BlogList(ListView):
    model = Post    
    template_name = "blogpost/blog_list.html"
    context_object_name = "blog_list"
    paginate_by = 6


class AuthorDetail(DetailView):
    model = User
    template_name = "blogpost/author_detail.html"
    context_object_name = "author"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.object
        context["data"] = author.posts.all()
        return context


class BlogDetail(DetailView):
    model = Post
    template_name = "blogpost/blog_detail.html"
    context_object_name = "content"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        context["comments"] = post.comments.all()
        return context


class CommentFun(LoginRequiredMixin, View):
    template_name = "blogpost/comments.html"

    def get(self, request, **kwargs):
        uname = self.request.user.first_name
        blog_id = kwargs["pk"]
        title = Post.objects.get(pk=blog_id).title
        form = CommentForm()
        context = {"id": blog_id, "title": title, "form": form, "uname": uname}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        blog_id = kwargs["pk"]
        content = request.POST.get("comment")
        if content:
            Comment.objects.create(
                commentblog_id=blog_id,
                comment=content,
                username=request.user,
            )
        return HttpResponseRedirect(reverse("blog-detail", kwargs={"pk": blog_id}))


class AuthorList(ListView):
    model = User
    template_name = "blogpost/author_list.html"
    context_object_name = "author_list"
    paginate_by = 5

    def get_queryset(self):
        queryset = User.objects.annotate(num_posts=Count("posts")).filter(
            num_posts__gt=0
        )
        return queryset


class Signup(CreateView):
    model = User
    template_name = "blogpost/sign_up.html"
    form_class = SignUpForm
    success_url = reverse_lazy("login")

    def get(self, request, **kwargs):
        form = SignUpForm()
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        fm = SignUpForm(request.POST)
        if fm.is_valid():
            fm.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return HttpResponseRedirect("/accounts/register/")


class BlogAdd(LoginRequiredMixin, View):
    template_name = "blogpost/blog_add.html"
    form_class = BlogAddForm

    def get(self, request, **kwargs):
        context = {
            "author": self.request.user.first_name,
            "form": self.form_class(),
        }
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        form = BlogAddForm(request.POST)
        if form.is_valid():
            form.instance.author = self.request.user
            form.save()
            return HttpResponseRedirect(
                reverse("author-detail", kwargs={"pk": request.user.id})
            )
        else:
            return render(request, self.template_name, {"form": form})


class SearchFun(ListView):
    template_name = "blogpost/search.html"
    model = Post
    context_object_name = "blog_list"

    def get(self, request):
        form = SearchForm()
        return render(request, "home", {"form": form})

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            word = form.cleaned_data["search"]
            queryset = Post.objects.filter(title__icontains=word)
            return render(request, self.template_name, {"blog_list": queryset})
        else:
            return render(request, "home", {"form": form})

demo/blogpost/templates/blogpost/author_detail.html
<!DOCTYPE html>
{% extends 'blogpost/base.html' %}

{% block blockname %}

<main class="container">
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark my-1">
        <div class="col-md-6 px-0">
            <h1 class="display-4 fst-italic">{{author.first_name}}</h1><br>
            <ul>
                <li><p class="lead my-0">Email - {{author.email}}</p></li>
                <li><p class="lead mb-0">Birth date - {{author.birth_date}}</p></li>
                <li><p class="lead mb-0">Country - {{author.country}}</p></li>
            </ul>
        </div>
    </div>
    <div class="container py-1">
        {% for blog in data %}
        {% if forloop.counter|divisibleby:2 %}
        <div class="col-md-6">
            <div class="h-100 p-5 text-white bg-dark rounded-3 my-2">
                <h2><a class="text-white bg-dark" href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></h2>
                <p class="text-white bg-dark">{{blog.pub_date}}</p>
            </div>
        </div>
        {% else %}
        <div class="col-md-6">
            <div class="h-100 p-5 bg-light border rounded-3 my-2">
                <h2><a class="text-dark" href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></h2>
                <p class="text-dark">{{blog.pub_date}}</p>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</main>

{% endblock blockname %}

demo/blogpost/templates/blogpost/author_list.html
{% extends 'blogpost/base.html' %}
{% block blockname %}
<div class="container"><h2>Bloggers</h2></div>
<div class="container py-1">
    {% for author in author_list %}
    {% if forloop.counter|divisibleby:2 %}
    <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3 my-2">
            <h2><a class="text-white bg-dark" href="{% url 'author-detail' author.pk %}">{{author.first_name}}</a></h2>
        </div>
    </div>
    {% else %}
    <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3 my-2">
            <h2><a class="text-dark" href="{% url 'author-detail' author.pk %}">{{author.first_name}}</a></h2>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>    
</main> 
{% if is_paginated %}
<div class="container py-2 d-flex justify-content-start">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}
{% endblock blockname %}      

demo/blogpost/templates/blogpost/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title></title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#d3dae1">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home'%}">Gadget Gyan</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if request.user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
                    <a class="nav-link" href="{% url 'blog-list'%}">Blogs </a>
                    <a class="nav-link" href="{% url 'author-list'%}">Bloggers </a>
                    <a class="nav-link" href="{% url 'blog-add' request.user.id %}">Add Post</a>
                    
                    {% else %}
                    <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
                    <a class="nav-link" href="{% url 'blog-list'%}">Blogs </a>
                    <a class="nav-link" href="{% url 'author-list'%}">Bloggers </a>
                    <a class="nav-link" href="/accounts/register/">Sign Up</a>
                    <a class="nav-link" href="/accounts/login/">Login</a>
                    {% endif %}
                    <form class="d-flex" action="{% url 'blog-search' %}" method="post">
                        {% csrf_token %}
                        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                      </form>
                </div>
                <ul class="navbar-nav ms-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="/accounts/logout/">Logout</a></li>
                    <li class="nav-item"><span class="nav-link">User ({{ request.user.first_name }})</span></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block blockname %}   

    {% endblock blockname %}
</body>

</html>

demo/blogpost/templates/blogpost/blog_add.html
{% extends 'blogpost/base.html' %}
{% block blockname %}

<body>
    <div class="account-pages mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-20 col-lg-10 col-xl-40">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="text-center w-75 m-auto">
                                <div class="auth-logo">
                                    <form action="{% url 'blog-add' user.id %}" method="post">
                                        {% csrf_token %}
                                        {% for field in form %}
                                    
                                          <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">{{field.label}}</label>
                                            <div></div>
                                                  {{ field }}

                                          </div>
                                        
                                          {% endfor %}
                                          <button type="submit" class="btn btn-primary">Submit</button>
                                      </form>
                                </div>
                            </div>  
                        </div>
                    </div>
                </div>
            </div>
</body>
    


{% endblock blockname %}

demo/blogpost/templates/blogpost/blog_detail.html
{% extends 'blogpost/base.html' %}

{% block blockname %}

<body>
  <main class="container">
    <div class="p-3 p-md-4 mb-3 my-2 text-white rounded bg-dark">
      <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">{{content.title}}</h1>
        <p class="lead my-3">{{content.pub_date}}</p>
        <p class="lead mb-0"><a href="{% url 'author-detail' content.author_id %}" class="text-white fw-bold">by -
            {{content.author.first_name}}</a></p>
      </div>
    </div>

    <div class="row mb-2">
      <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-0">{{content.blog}}</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="h-100 p-3 w-60 bg-light border rounded-3">
      <p class="">Commentbox</p>
      {% for comment in comments %}
      <div class="comment-content">
        <div class="comment-author">
          <span class="comment-link">{{comment.username.first_name}} </span>
          <span class="comment-meta commentmetadata">
            <span class="comment-date">({{comment.comment_date}})</span>
          </span>
        </div>
        <div class="clr"></div>
        <div class="comment-entry">
          <div class="comment-content">
            <p>{{comment.comment}}</p>
          </div>
        </div>
      </div>
      {% endfor %} 
      <a href="{% url 'comment' content.pk %}">Comment your thoughts</a>
      
    </div>
  </main>

</body>

{% endblock blockname %}

demo/blogpost/templates/blogpost/blog_list.html
<!DOCTYPE html>
{% extends 'blogpost/base.html' %}
<head>
    <title>Blog List</title>
</head>
{% block blockname %}

<main>
  <div class="container py-4">
    {% for blog in blog_list %}
      {% if forloop.counter|divisibleby:2 %}
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3 my-2">
          <h2><a class="text-dark" href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></h2>
          <p class="text-dark">{{blog.pub_date}}</p>
          <p><a class="text-dark" href="{% url 'author-detail' blog.author_id %}">{{blog.author.first_name}}</a></p>
        </div>
      </div>
      {% else %}
        <div class="col-md-6">
          <div class="h-100 p-5 text-white bg-dark rounded-3 my-2">
            <h2><a class="text-white bg-dark" href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></h2>
            <p class="text-white bg-dark">{{blog.pub_date}}</p>
            <p><a class="text-white bg-dark" href="{% url 'author-detail' blog.author_id %}">{{blog.author.first_name}}</a></p>
          </div>
        </div>
        {% endif %}
        {% endfor %}
  </div>  
</main> 
{% if is_paginated %}
<div class="container py-2 d-flex justify-content-start">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}
  {% endblock blockname %}      

demo/blogpost/templates/blogpost/comments.html
 {% extends 'blogpost/base.html' %}

 {% block blockname %}
 <div class="container my-5">
     <div class="text-center">
         <h1>Add Comments about <a href="{% url 'blog-detail' id %}">{{ title }}</a></h1>
         <form method="post" action="{% url 'comment' id %}">
             {% csrf_token %}
             {% for field in form %}
             <div>
                 <p>
                     <label>
                         {{ field.label }}
                         {% if field.label == "Username" %}
                             <input value="{{ uname }}" required readonly>
                         {% else %}
                             {{ field }}
                         {% endif %}
                     </label>
                 </p>
             </div>
             {% endfor %}
 
             <input type="submit" value="Post Comment">
         </form>
     </div>
 </div>
 {% endblock blockname %}
 

demo/blogpost/templates/blogpost/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

demo/blogpost/templates/blogpost/home.html
{% extends 'blogpost/base.html' %}

{% block blockname %}
<div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <h2>Welcome to World of Gadgets</h2>
    </header>
<main>
  <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center" style="background-color:#d3dae1">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 fw-bold">Gadget Gyan</h1>
      <p class="lead fw-normal">Using this website you can get information about latest technologies and gadgets.</p>
      <h2 class="display-4 fw-normal"></h2>
      <a class="btn btn-outline-secondary" href= "{% url 'blog-list' %}">Read More</a>
    </div>
    <div class="product-device shadow-sm d-none d-md-block"></div>
    <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  </div>
</main>
</div>

<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"></circle><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"></path></svg>
      <small class="d-block mb-3 text-muted">© 2017–2021</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Cool stuff</a></li>
        <li><a class="link-secondary" href="#">Random feature</a></li>
        <li><a class="link-secondary" href="#">Team feature</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Follow us on</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Pinterest</a></li>
        <li><a class="link-secondary" href="#">Instagram</a></li>
        <li><a class="link-secondary" href="#">Facebook</a></li>
        <li><a class="link-secondary" href="#">Twitter</a></li>
        <li><a class="link-secondary" href="#">YouTube</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Business</a></li>
        <li><a class="link-secondary" href="#">Education</a></li>
        <li><a class="link-secondary" href="#">Government</a></li>
        <li><a class="link-secondary" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Team</a></li>
        <li><a class="link-secondary" href="#">Locations</a></li>
        <li><a class="link-secondary" href="#">Privacy</a></li>
        <li><a class="link-secondary" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>






<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

{% endblock blockname %}

demo/blogpost/templates/blogpost/search.html
<!DOCTYPE html>
{% extends 'blogpost/base.html' %}
<head>
    <title>Blog List</title>
</head>
{% block blockname %}

<main>
  <div class="container py-4">
    {% if blog_list %}
    {% for blog in blog_list %}
      {% if forloop.counter|divisibleby:2 %}
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3 my-2">
          <h2><a class="text-dark" href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></h2>
          <p class="text-dark">{{blog.pub_date}}</p>
          <p><a class="text-dark" href="{% url 'author-detail' blog.author_id %}">{{blog.author.first_name}}</a></p>
        </div>
      </div>
      {% else %}
        <div class="col-md-6">
          <div class="h-100 p-5 text-white bg-dark rounded-3 my-2">
            <h2><a class="text-white bg-dark" href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></h2>
            <p class="text-white bg-dark">{{blog.pub_date}}</p>
            <p><a class="text-white bg-dark" href="{% url 'author-detail' blog.author_id %}">{{blog.author.first_name}}</a></p>
          </div>
        </div>
        {% endif %}
        {% endfor %}
    {% else %}
      <p>No matching blog posts found.</p>
    {% endif %}    
  </div>  
</main> 

  {% endblock blockname %}      

demo/blogpost/templates/blogpost/sign_up.html
{% extends 'blogpost/base.html' %}

{% block blockname %}

<body>
    <div class="account-pages mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <div class="card">

                        <div class="card-body p-4">
                            <form action="" method="post"> 
                                {% csrf_token %} 
                                
                                {% for field in form %}
                                    <div id="div_id_first_name" class="form-group"> <label for="id_first_name" class=" requiredField">
                                        {{field.label}}<span class="asteriskField">*</span> </label>
                                    <div> {{field}}</div>
                                    </div>
                                {% endfor %}    
                                <div class="text-center d-grid mt-2">
                                    <button class="btn btn-primary" type="submit"> Sign Up » </button>
                                </div>

                            </form>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-12 text-center">
                            <p>Already have account? <a href="/accounts/login/"><b>Sign In</b></a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body> 


{% endblock blockname %}